SELECT 
    A.CAR_ID, 
    A.CAR_TYPE, 
    ROUND(A.DAILY_FEE * 30 * (1 - COALESCE(C.DISCOUNT_RATE, 0) / 100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_TYPE IN ('SUV', '세단')
  AND C.DURATION_TYPE = '30일 이상'
  AND NOT EXISTS (
      SELECT 1 
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
      WHERE A.CAR_ID = B.CAR_ID
        AND B.START_DATE <= '2022-11-30' 
        AND B.END_DATE >= '2022-11-01'
  )
  AND (A.DAILY_FEE * 30 * (1 - COALESCE(C.DISCOUNT_RATE, 0) / 100)) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;