SELECT (
    CASE 
    WHEN MONTH(DIFFERENTIATION_DATE) IN(1,2,3) THEN CONCAT(1,'Q')
    WHEN MONTH(DIFFERENTIATION_DATE) IN(4,5,6) THEN CONCAT(2,'Q')
    WHEN MONTH(DIFFERENTIATION_DATE) IN(7,8,9) THEN CONCAT(3,'Q')
    WHEN MONTH(DIFFERENTIATION_DATE) IN(10,11,12) THEN CONCAT(4,'Q')
    END
)AS QUARTER , 
COUNT(*) AS ECOLI_COUNT 
FROM ECOLI_DATA 
GROUP BY QUARTER
ORDER BY QUARTER ASC;